/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */

export type AuthenticationExceptionResponse = {
  /** Error overview. */
  message: string;
};
