/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */

export * from './addMusicRequest';
export * from './authLoginRequest';
export * from './authRegisterRequest';
export * from './authResource';
export * from './authenticationExceptionResponse';
export * from './authorizationExceptionResponse';
export * from './musicGetPendingMusics200';
export * from './musicGetPendingMusics200Meta';
export * from './musicGetPendingMusicsOrderBy';
export * from './musicGetPendingMusicsParams';
export * from './musicIndex200';
export * from './musicIndex200Meta';
export * from './musicIndexOrderBy';
export * from './musicIndexParams';
export * from './musicResource';
export * from './validationExceptionResponse';
export * from './validationExceptionResponseErrors';