/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */
import type { MusicResource } from './musicResource';
import type { MusicIndex200Meta } from './musicIndex200Meta';

export type MusicIndex200 = {
  data: MusicResource[];
  meta: MusicIndex200Meta;
};
