/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */
import type { MusicResource } from './musicResource';
import type { MusicGetPendingMusics200Meta } from './musicGetPendingMusics200Meta';

export type MusicGetPendingMusics200 = {
  data: MusicResource[];
  meta: MusicGetPendingMusics200Meta;
};
