/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */
import type { MusicGetPendingMusicsOrderBy } from './musicGetPendingMusicsOrderBy';

export type MusicGetPendingMusicsParams = {
limit?: number;
page?: number;
orderBy?: MusicGetPendingMusicsOrderBy;
};
