/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */

export interface MusicResource {
  id: number;
  title: string;
  youtube_id: string;
  formatted_views: string;
  thumbnail: string;
  url: string;
}
