/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * Tião Carreiro - Api
 * OpenAPI spec version: 0.0.1
 */

export type MusicGetPendingMusicsOrderBy = typeof MusicGetPendingMusicsOrderBy[keyof typeof MusicGetPendingMusicsOrderBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MusicGetPendingMusicsOrderBy = {
  views: 'views',
  created_at: 'created_at',
} as const;
